# spring:
#   redis:
#     host: ${SPRING_REDIS_HOST}
#     port: ${SPRING_REDIS_PORT}
#     password: ${SPRING_REDIS_PASSWORD}


spring:
  datasource:
    url: jdbc:mysql://rdsendpoin:3306/mydb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
